language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: m3CKznssMPOKCSGCKs5qDDkjaDgzSLEf8udGE2cE/or/jpAfGU21NvbLqbQRH9DShJmYvd/XB3UOODdxRrLcfvQH4viAJmUPQrLSct97D9p2fQrPangKXzHXpdNPJ7m4Qq1zA/L4BOQ2r30Y91KeNKl6TS0IC9pJFyxlLgOSX8De9GOblgOAVUxCc+UK1X14TKlj1RkK6+K0HbxI+E3CRQHHQ92UA9WwAK6JtBsky/CgQuCR3VVlWyntnk69Pa6bf2HWg48I0IqYSAK13lAeSPhYpZEUM4qjjCdI0QmJ7r6yRJKu1ELQriHLYbsSL34I9lc7OmIn8RLXMhPtRLTctWcuH+rZF9gaMo/KQGwU2/mPe3rWmwYHROS37etUO2ie1wg0KpWcvtV4snkIC7MGj3VhgBQqRwy3LoSdbGdK3CRvX8Ig3DCx5ptrZIQW+iHrMlzB7atvHsuOTa3Vl7rZVwA22/xUReC+cdf8Ar1dPndF1KCRCHYLO6fhlTNxdwLBAEm7cWO7roJGJV1ikh+ST79Vd1/xohs53BV81QkLoXiXjFN0c9YmB3iNVVAqUZL0wmtOr8c8lSH0sKY+BrfQKUxnkg181ks8eRDOOEVhax59tmaQqdJqfTFTYjEX/tdTDGI4wDFWFvBs3qIk+5GurZu6C4ynIKv4VCTej3J15KU=
  app: polar-crag-99603
  on:
    repo: thinkful-ei21/james-noteful-app-v3
